spring:
  application:
    name: service-admin
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/kukumusic?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.xq.serviceadmin.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/